---
- name: Check if Azure CLI is installed.
  shell: command -v az >/dev/null 2>&1
  ignore_errors: true
  register: az_cli_installed

- block:
  - name: Add an Apt signing key for Azure CLI.
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
  - name: Add repository for Azure CLI.
    apt_repository:
      repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ansible_distribution_release}} main
      state: present
  - name: Install Azure CLI.
    apt:
      update_cache: yes
      name: azure-cli
      state: present
  when: az_cli_installed is failed and ansible_distribution == 'Ubuntu'
  become: true
