---
# Prerequisites on localhost (Ansible Controller) to run Ansible AWS modules

- block:

  - name: ensure python pip is installed.
    include_tasks: install-pip.yml

  - name: ensure prerequisite pip packages
    pip:
      name: '{{item}}'
      state: present
    with_items:
    - boto
    - boto3
  become: true

- name: Fail if Ansible < 2.5
  fail: msg="Ansible 2.5+ required"
  when: ansible_version.major <= 2 and ansible_version.minor < 5
